/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import java.util.ArrayList;

/**
 *
 * @author antonyarce
 */
public class ventana extends javax.swing.JFrame {
    
    String botonPresionado;
    String nombreEsquema;
    String atributoColumna = "nombre";
    String nombreColumna = "nombreColumna";
    String tipoColumna = "String";
    int largoColumna = 15;
    Esquema esquema;
    Columna columna;
    ArrayList<Esquema> esquemas = new ArrayList<Esquema>();
    String nombreBusquedaEsq;
    int tamañoEsquemas;
    int indiceEsquemas;
    int indiceBorrarEsq;
    int indiceAgregarDat;
    int tamañoColumnas;
    boolean esquemaEncontrado = false;
    int indiceColumnas = 0;
    Object dato;
    ArrayList<Object> datos = new ArrayList<Object>();
   

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonCrearEsq = new javax.swing.JButton();
        botonAgregarCol = new javax.swing.JButton();
        botonAgregarDat = new javax.swing.JButton();
        botonBuscarDat = new javax.swing.JButton();
        botonBorrarDat = new javax.swing.JButton();
        botonBorrarEsq = new javax.swing.JButton();
        botonCrearInd = new javax.swing.JButton();
        botonBorrarInd = new javax.swing.JButton();
        campoIntro = new javax.swing.JTextField();
        botonIntro = new javax.swing.JButton();
        botonListo = new javax.swing.JButton();
        textoInstruccion = new javax.swing.JLabel();
        textoMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonCrearEsq.setText("Crear esquema");
        botonCrearEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearEsqActionPerformed(evt);
            }
        });

        botonAgregarCol.setText("Agregar columnas");
        botonAgregarCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarColActionPerformed(evt);
            }
        });

        botonAgregarDat.setText("Agregar datos");
        botonAgregarDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarDatActionPerformed(evt);
            }
        });

        botonBuscarDat.setText("Buscar datos");

        botonBorrarDat.setText("Borrar datos");
        botonBorrarDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarDatActionPerformed(evt);
            }
        });

        botonBorrarEsq.setText("Borrar esquema");
        botonBorrarEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarEsqActionPerformed(evt);
            }
        });

        botonCrearInd.setText("Crear indice");

        botonBorrarInd.setText("Borrar indice");

        botonIntro.setText("Introducir");
        botonIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIntroActionPerformed(evt);
            }
        });

        botonListo.setText("OK");
        botonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscarDat)
                    .addComponent(botonBorrarDat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCrearEsq)
                    .addComponent(botonAgregarCol)
                    .addComponent(botonAgregarDat)
                    .addComponent(botonBorrarEsq)
                    .addComponent(botonCrearInd))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonBorrarInd)
                        .addGap(77, 77, 77)
                        .addComponent(textoMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(textoInstruccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campoIntro)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonIntro)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonListo)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCrearEsq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBorrarEsq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAgregarCol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonAgregarDat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscarDat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBorrarDat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCrearInd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrarInd)
                    .addComponent(botonListo)
                    .addComponent(textoMensaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(textoInstruccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoIntro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonIntro)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearEsqActionPerformed
        // TODO add your handling code here:
        botonPresionado = "botonCrearEsq";
        textoInstruccion.setText("Introducir el nombre del esquema:");
        
    }//GEN-LAST:event_botonCrearEsqActionPerformed

    private void botonBorrarDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBorrarDatActionPerformed

    private void botonIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIntroActionPerformed
        // TODO add your handling code here:
       switch(botonPresionado){
            
           case "botonCrearEsq":
               nombreEsquema = campoIntro.getText();
               esquema = new Esquema(nombreEsquema);
               textoMensaje.setText("Esquema creado, guarde el esquema");
               textoInstruccion.setText("");
               campoIntro.setText("");
               break;
           
           case "botonAgregarCol":
               switch(atributoColumna){
                   case "nombre":
                       nombreColumna = campoIntro.getText();
                       atributoColumna = "tipo";
                       textoInstruccion.setText("Introduzca el tipo de columna");
                       campoIntro.setText("");
                       break;
                    
                   case "tipo":
                       tipoColumna = campoIntro.getText();
                       atributoColumna = "largo";
                       textoInstruccion.setText("Introduzca el largo de los valores de la columna");
                       campoIntro.setText("");
                       break;
                       
                   case "largo":
                       largoColumna = Integer.parseInt(campoIntro.getText());
                       textoInstruccion.setText("Guarde la columna");
                       campoIntro.setText("");
                       break;

               }
               
               break;
           
           case "botonBorrarEsq":
               nombreBusquedaEsq = campoIntro.getText();
               tamañoEsquemas = esquemas.size();
               indiceEsquemas = 0;
               textoMensaje.setText("No se ha encontrado el esquema..");
               while (indiceEsquemas < tamañoEsquemas){
                   if (nombreBusquedaEsq.equals(esquemas.get(indiceEsquemas).getNombre())){
                        indiceBorrarEsq = indiceEsquemas;
                        textoInstruccion.setText("");
                        campoIntro.setText("");
                        textoMensaje.setText("Esquema ´"+ esquemas.get(indiceBorrarEsq).getNombre()+ "´ encontrado, desea borrarlo?");
                        break;
                   }
                   indiceEsquemas ++;
               }
               break;
            
           case "botonAgregarDat":
               if (esquemaEncontrado){
                   dato = campoIntro.getText();
                   datos.add(dato);
                   campoIntro.setText("");
                   indiceColumnas ++;
                   //textoMensaje.setText("");
                   if (indiceColumnas < esquemas.get(indiceAgregarDat).columnas.size()){
                        textoInstruccion.setText("Introduzca el dato de la columna: "+ esquemas.get(indiceAgregarDat).columnas.get(indiceColumnas).nombre);
                   } else {
                  textoMensaje.setText("Desea agregar los datos introducidos?");
                  textoInstruccion.setText("");
                  indiceColumnas = 0;
                   }     
                   
               } else{
               nombreBusquedaEsq = campoIntro.getText();
               tamañoEsquemas = esquemas.size();
               indiceEsquemas = 0;
               textoMensaje.setText("No se ha encontrado el esquema..");
               while (indiceEsquemas < tamañoEsquemas){
                   if (nombreBusquedaEsq.equals(esquemas.get(indiceEsquemas).getNombre())){
                        indiceAgregarDat = indiceEsquemas;
                        textoInstruccion.setText("Introduzca el dato de la columna: "+ esquemas.get(indiceAgregarDat).columnas.get(indiceColumnas).nombre);
                        campoIntro.setText("");
                        esquemaEncontrado = true;
                        textoMensaje.setText("Esquema ´"+ esquemas.get(indiceAgregarDat).getNombre()+ "´ encontrado, agregue los datos");
                        break;
                   }
                   indiceEsquemas ++;
               }   
               }
               break; 
       }
    }//GEN-LAST:event_botonIntroActionPerformed

    private void botonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListoActionPerformed
        // TODO add your handling code here:
        // Se guarda el esquema
        switch(botonPresionado){
            case "botonCrearEsq":
                esquemas.add(esquema);
                textoMensaje.setText("Esquema guardado, agregue las columnas");
                break;
            case "botonAgregarCol":
                columna = new Columna(nombreColumna,tipoColumna,largoColumna);
                esquema.añadirColumna(columna);
                textoMensaje.setText("Columna guardada");
                atributoColumna = "nombre";
                textoInstruccion.setText("Introduzca el nombre de la columna");
                String nombreColumna = "nombreColumna";
                String tipoColumna = "String";
                int largoColumna = 15;
                break;
            
            case "botonBorrarEsq":
                esquemas.remove(indiceBorrarEsq);
                textoMensaje.setText("Se ha borrado el esquema ");
                break;
                
            case "botonAgregarDat":
                if (esquema.agregarDatos(datos)){
                    textoMensaje.setText("Se agregaron los datos");
                } else {
                    textoMensaje.setText("Datos invalidos");
                }              
                break;
                        
            
        }
        
    }//GEN-LAST:event_botonListoActionPerformed

    private void botonAgregarColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarColActionPerformed
        // TODO add your handling code here:
        botonPresionado = "botonAgregarCol";
        switch(atributoColumna){
            case "nombre":
                textoInstruccion.setText("Introduzca el nombre de la columna");
                break;       
        }
               

    }//GEN-LAST:event_botonAgregarColActionPerformed

    private void botonBorrarEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarEsqActionPerformed
        // TODO add your handling code here:
        botonPresionado = "botonBorrarEsq";
        textoMensaje.setText("");
        textoInstruccion.setText("Introduzca el nombre del esquema a borrar");
        
    }//GEN-LAST:event_botonBorrarEsqActionPerformed

    private void botonAgregarDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarDatActionPerformed
        // TODO add your handling code here:
        botonPresionado = "botonAgregarDat";
        textoInstruccion.setText("Introduzca el nombre del esquema para agregar datos");
        textoMensaje.setText("");
    }//GEN-LAST:event_botonAgregarDatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarCol;
    private javax.swing.JButton botonAgregarDat;
    private javax.swing.JButton botonBorrarDat;
    private javax.swing.JButton botonBorrarEsq;
    private javax.swing.JButton botonBorrarInd;
    private javax.swing.JButton botonBuscarDat;
    private javax.swing.JButton botonCrearEsq;
    private javax.swing.JButton botonCrearInd;
    private javax.swing.JButton botonIntro;
    private javax.swing.JButton botonListo;
    private javax.swing.JTextField campoIntro;
    private javax.swing.JLabel textoInstruccion;
    private javax.swing.JLabel textoMensaje;
    // End of variables declaration//GEN-END:variables
}

